ALTER TABLE QueraEcoPlus.COURSE_HW ADD CONSTRAINT private_class_HW_check
CHECK (EXISTS(SELECT * FROM QueraEcoPlus.COURSE WHERE COURSE.COURSE_ID = COURSE_HW.COURSE_ID AND COURSE.IS_PUBLIC = 0) 
AND NOT EXISTS(SELECT * FROM QueraEcoPlus.CRS_PARTICIPANTS WHERE CRS_PARTICIPANTS.COURSE_ID = COURSE_HW.COURSE_ID AND CRS_PARTICIPANTS.USER_ID = COURSE_HW.USER_ID));







