
/*
* COMPANY_REGISTRATION_ID FOREIGN KEY ON DELETE AND ON UPDATE CASCADE
* ADVERTISMENT FOREIGN KEY ON DELETE AND ON UPDATE CASCADE
* ADVERTISMENT FOREIGN KEY ON DELETE AND ON UPDATE CASCADE
* USER FOREIGN KEY ON DELETE AND ON UPDATE CASCADE
* COURSE FOREIGN KEY ON DELETE AND ON UPDATE CASCADE
* COURSE_HW FOREIGN KEY ON DELETE AND ON UPDATE CASCADE
* NOTIFICATION FOREIGN KEY ON DELETE AND ON UPDATE CASCADE
*/
CREATE DATABASE QueraEcoPlus;

CREATE TABLE QueraEcoPlus.SKILLS(SKILL_NAME varchar(10) ,SKILL_TYPE varchar(10), PRIMARY KEY (SKILL_NAME));

CREATE TABLE QueraEcoPlus.COMPANY(COMPANY_REGISTRATION_ID varchar(10) ,ADDR varchar(10),
                    COMPANY_NAME varchar(10),INFO_FILE_LOCATION varchar(10), 
                    PHONE_1 varchar(10) ,PHONE_2 varchar(10),PHONE_3 varchar(10), PRIMARY KEY (COMPANY_REGISTRATION_ID));


CREATE TABLE QueraEcoPlus.ADVERTISEMENT(COMPANY_REGISTRATION_ID varchar(10) , ADD_ID varchar(10),
INFO_FILE_LOCATION varchar(10), EXPERIENCE_YR INT,IS_PART_TIME BOOLEAN,
WORK_HOURS INT, BEGINNING_DATE DATETIME, EXP_DATE DATETIME, 
PRIMARY KEY (COMPANY_REGISTRATION_ID, ADD_ID), FOREIGN KEY (COMPANY_REGISTRATION_ID) REFERENCES QueraEcoPlus.COMPANY(COMPANY_REGISTRATION_ID));


CREATE TABLE QueraEcoPlus.ADV_REQUIREMENTS(COMPANY_REGISTRATION_ID varchar(10), ADD_ID varchar(10), 
SKILL_NAME varchar(10), SKILL_LEVEL INT, PRIMARY KEY(COMPANY_REGISTRATION_ID, ADD_ID, SKILL_NAME),
FOREIGN KEY(COMPANY_REGISTRATION_ID, ADD_ID) REFERENCES ADVERTISEMENT(COMPANY_REGISTRATION_ID, ADD_ID),
FOREIGN KEY(SKILL_NAME) REFERENCES SKILLS(SKILL_NAME));


CREATE TABLE QueraEcoPlus.ADV_RELATIVE_SKILLS(COMPANY_REGISTRATION_ID varchar(10), ADD_ID varchar(10), 
SKILL_NAME varchar(10), PRIMARY KEY(COMPANY_REGISTRATION_ID, ADD_ID, SKILL_NAME),
FOREIGN KEY(COMPANY_REGISTRATION_ID, ADD_ID) REFERENCES ADVERTISEMENT(COMPANY_REGISTRATION_ID, ADD_ID),
FOREIGN KEY(SKILL_NAME) REFERENCES SKILLS(SKILL_NAME));

CREATE TABLE QueraEcoPlus.USER(USER_ID INT NOT NULL AUTO_INCREMENT,EMAIL_ADD varchar(15),
FIRST_NAME varchar(10),LAST_NAME varchar(10),NATIONAL_ID varchar(10), PRIMARY KEY (USER_ID));

CREATE TABLE QueraEcoPlus.CV(USER_ID INT, BIRTH_DATE DATETIME, GENDER varchar(3), IS_MARRIED BOOLEAN,
INFO_FILE_LOCATION varchar(20), ADDR_STATE varchar(10), ADDR_CITY varchar(10),ADDR_AREA varchar(10),
PRIMARY KEY(USER_ID), FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID));

CREATE TABLE QueraEcoPlus.CV_PHONES(user_id INT, PHONE_NUMBER varchar(15), 
PRIMARY KEY(USER_ID, PHONE_NUMBER), FOREIGN KEY(USER_ID) REFERENCES CV(USER_ID));

CREATE TABLE QueraEcoPlus.CV_PROJ_LINKS(user_id INT, URL varchar(20), 
PRIMARY KEY(USER_ID, URL), FOREIGN KEY(USER_ID) REFERENCES CV(USER_ID));

CREATE TABLE QueraEcoPlus.CV_SKILLS(user_id INT, SKILL_NAME varchar(10), SKILL_LEVEL INT,
PRIMARY KEY(USER_ID, SKILL_NAME), 
FOREIGN KEY(USER_ID) REFERENCES CV(USER_ID), 
FOREIGN KEY(SKILL_NAME) REFERENCES SKILLS(SKILL_NAME));


CREATE TABLE QueraEcoPlus.CV_EDU_HISTORY(user_id INT, CRS_NAME varchar(15), ORG_NAME varchar(10),
CERTIFATE_URL varchar(20), SCORE INT, 
PRIMARY KEY(USER_ID, CRS_NAME),
FOREIGN KEY(USER_ID) REFERENCES CV(USER_ID));

CREATE TABLE QueraEcoPlus.CV_WORK_INFO(user_id INT, DESIRED_INCOME INT,
IS_PART_TIME BOOLEAN , WORK_HOURS INT, DESIRED_JOB_TITLE varchar(10),
WORK_EXP_YR INT, EMPLOYMENT_STATUS varchar(10), 
PRIMARY KEY(USER_ID), 
FOREIGN KEY(USER_ID) REFERENCES CV(USER_ID));

CREATE TABLE QueraEcoPlus.CV_WORK_INFO_INTRESTS(user_id INT, SKILL_NAME varchar(10),
PRIMARY KEY(USER_ID,SKILL_NAME), 
FOREIGN KEY(USER_ID) REFERENCES CV(USER_ID),
FOREIGN KEY(SKILL_NAME) REFERENCES SKILLS(SKILL_NAME));

CREATE TABLE QueraEcoPlus.REQUESTS(user_id INT, COMPANY_REGISTRATION_ID varchar(10), ADD_ID varchar(10),STATUS varchar(20),
PRIMARY KEY(USER_ID,COMPANY_REGISTRATION_ID, ADD_ID), 
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID), 
FOREIGN KEY(COMPANY_REGISTRATION_ID, ADD_ID) REFERENCES ADVERTISEMENT(COMPANY_REGISTRATION_ID, ADD_ID));

CREATE TABLE QueraEcoPlus.COURSE(COURSE_ID varchar(10), COURSE_NAME varchar(15), BEGINNING_DATE DATETIME,
FINISHING_DATE DATETIME, PRIMARY KEY(COURSE_ID));

CREATE TABLE QueraEcoPlus.COURSE_SPONSOR(COURSE_ID varchar(10), COMPANY_REGISTRATION_ID varchar(10),
PRIMARY KEY(COURSE_ID, COMPANY_REGISTRATION_ID),
FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSE_ID),
FOREIGN KEY(COMPANY_REGISTRATION_ID) REFERENCES COMPANY(COMPANY_REGISTRATION_ID));

CREATE TABLE QueraEcoPlus.COURSE_MATERIAL_PROVIDER(COURSE_ID varchar(10), user_id INT,
ACCESS_LEVEL varchar(10), PRIMARY KEY(COURSE_ID,USER_ID),
FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSE_ID), FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID));

CREATE TABLE QueraEcoPlus.COURSE_MATERIAL(COURSE_ID varchar(10), MATERIAL_ID varchar(10), FILE_LOCATION varchar(20), UPLOAD_DATE DATETIME,
PRIMARY KEY(COURSE_ID, MATERIAL_ID), 
FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSE_ID));
CREATE TABLE QueraEcoPlus.CRS_PARTICIPANTS(user_id INT, COURSE_ID varchar(10), 
PRIMARY KEY(USER_ID, COURSE_ID),
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSE_ID));
CREATE TABLE QueraEcoPlus.COURSE_HW(COURSE_ID varchar(10), HW_TITLE varchar(15), DEADLINE_DATE DATETIME,
PENALTY_TIME_SEG_HOURS INT, PENALTY_VALUE DOUBLE,OPENING_DATE DATETIME, CLOSING_DATE DATETIME,
HW_DESCRIPTION_FILE_LOCATION varchar(20), FILE_SIZE_LIMIT INT,
PRIMARY KEY(COURSE_ID, HW_TITLE), FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSE_ID));

CREATE TABLE QueraEcoPlus.HW_ACCEPTABLE_FORMATS(COURSE_ID varchar(10), HW_TITLE varchar(15), FORMAT_NAME varchar(10),
PRIMARY KEY(COURSE_ID,HW_TITLE,FORMAT_NAME), 
FOREIGN KEY(COURSE_ID,HW_TITLE) REFERENCES COURSE_HW(COURSE_ID, HW_TITLE));

CREATE TABLE QueraEcoPlus.HW_DELIVERY(COURSE_ID varchar(10), HW_TITLE varchar(15), user_id INT,
DELIVARY_DATE DATETIME , FILE_LOCATION varchar(20), 
PRIMARY KEY(COURSE_ID, HW_TITLE, USER_ID),
FOREIGN KEY(COURSE_ID,HW_TITLE) REFERENCES COURSE_HW(COURSE_ID, HW_TITLE),
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID));

CREATE TABLE QueraEcoPlus.PROBLEM(PROBLEM_ID varchar(10), PROBLEM_TITLE varchar(15),
DESCRIPTION_FILE_LOCATION varchar(20), DIFFICULTY_LEVEL INT, 
PRIMARY KEY(PROBLEM_ID));

CREATE TABLE QueraEcoPlus.PROBLEM_SKILL(PROBLEM_ID varchar(10), SKILL_NAME varchar(10),
DIFFICULTY_LEVEL INT, 
PRIMARY KEY(PROBLEM_ID, SKILL_NAME), 
FOREIGN KEY(PROBLEM_ID) REFERENCES PROBLEM(PROBLEM_ID),
FOREIGN KEY(SKILL_NAME) REFERENCES SKILLS(SKILL_NAME));

CREATE TABLE QueraEcoPlus.CONTEST(CONTEST_ID varchar(10), CONTEST_TITLE varchar(20),
DESCRIPTION_FILE_LOCATION varchar(20), BEGINNING_DATE DATETIME,ENDING_DATE DATETIME, IS_PUBLIC BOOLEAN,
PRIMARY KEY(CONTEST_ID));

CREATE TABLE QueraEcoPlus.CONTEST_PROBLEMS(CONTEST_ID varchar(10), PROBLEM_ID varchar(10), SCORE INT,
PRIMARY KEY(CONTEST_ID, PROBLEM_ID),
FOREIGN KEY(PROBLEM_ID) REFERENCES PROBLEM(PROBLEM_ID),
FOREIGN KEY(CONTEST_ID) REFERENCES CONTEST(CONTEST_ID));

CREATE TABLE QueraEcoPlus.CONTEST_COURSE(COURSE_ID varchar(10), CONTEST_ID varchar(10),
PRIMARY KEY(COURSE_ID, CONTEST_ID),
FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSE_ID),
FOREIGN KEY(CONTEST_ID) REFERENCES CONTEST(CONTEST_ID));

CREATE TABLE QueraEcoPlus.CONTEST_SPONSOR(CONTEST_ID varchar(10), COMPANY_REGISTRATION_ID varchar(10),
PRIMARY KEY(CONTEST_ID, COMPANY_REGISTRATION_ID),
FOREIGN KEY(CONTEST_ID) REFERENCES CONTEST(CONTEST_ID),
FOREIGN KEY(COMPANY_REGISTRATION_ID) REFERENCES COMPANY(COMPANY_REGISTRATION_ID));

CREATE TABLE QueraEcoPlus. ACTIVITY_HISTORY_PROBLEMS(user_id INT, PROBLEM_ID varchar(10), score INT,
PRIMARY KEY(USER_ID, PROBLEM_ID),
FOREIGN KEY(USER_ID) REFERENCES CV(USER_ID),
FOREIGN KEY(PROBLEM_ID) REFERENCES PROBLEM(PROBLEM_ID));

CREATE TABLE QueraEcoPlus.ACTIVITY_HISTORY_CONTEST(user_id INT, CONTEST_ID varchar(10), SCORE INT,
RNK INT, PRIMARY KEY(USER_ID, CONTEST_ID), 
FOREIGN KEY(USER_ID) REFERENCES CV(USER_ID), 
FOREIGN KEY(CONTEST_ID) REFERENCES CONTEST(CONTEST_ID));

CREATE TABLE QueraEcoPlus.NOTIFICATION(NOTIFICATION_ID varchar(10), CREATION_DATE DATETIME, BODY TEXT(500),
PRIMARY KEY(NOTIFICATION_ID));

CREATE TABLE QueraEcoPlus.USER_NOTIFICATION(NOTIFICATION_ID varchar(10), user_id INT,
PRIMARY KEY(NOTIFICATION_ID),
FOREIGN KEY(NOTIFICATION_ID) REFERENCES NOTIFICATION(NOTIFICATION_ID),
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID));

CREATE TABLE QueraEcoPlus.NEW_ADD_NOTIF(NOTIFICATION_ID varchar(10),COMPANY_REGISTRATION_ID varchar(10), ADD_ID varchar(10),
PRIMARY KEY(NOTIFICATION_ID),
FOREIGN KEY(NOTIFICATION_ID) REFERENCES USER_NOTIFICATION(NOTIFICATION_ID),
FOREIGN KEY(COMPANY_REGISTRATION_ID, ADD_ID) REFERENCES ADVERTISEMENT(COMPANY_REGISTRATION_ID, ADD_ID)
                                    ON DELETE SET NULL 
                                    ON UPDATE SET NULL);

CREATE TABLE QueraEcoPlus.REQUEST_STATUS_UPDATE(NOTIFICATION_ID varchar(10),user_id INT,
COMPANY_REGISTRATION_ID varchar(10), ADD_ID varchar(10), 
PRIMARY KEY(NOTIFICATION_ID),
FOREIGN KEY(NOTIFICATION_ID) REFERENCES NOTIFICATION(NOTIFICATION_ID),
FOREIGN KEY(USER_ID, COMPANY_REGISTRATION_ID, ADD_ID) REFERENCES REQUESTS(USER_ID, COMPANY_REGISTRATION_ID, ADD_ID)
                                    ON DELETE SET NULL 
                                    ON UPDATE SET NULL);

CREATE TABLE QueraEcoPlus.NEW_REQUEST_NOTIF(NOTIFICATION_ID varchar(10), user_id INT, 
COMPANY_REGISTRATION_ID varchar(10), ADD_ID varchar(10),
PRIMARY KEY(NOTIFICATION_ID),
FOREIGN KEY(NOTIFICATION_ID) REFERENCES NOTIFICATION(NOTIFICATION_ID),
FOREIGN KEY(USER_ID,COMPANY_REGISTRATION_ID, ADD_ID) REFERENCES REQUESTS(USER_ID, COMPANY_REGISTRATION_ID, ADD_ID)
                                    ON DELETE SET NULL 
                                    ON UPDATE SET NULL);