-- DROP DATABASE QueraEcoPlus;

-- SELECT * FROM USER;

-- SELECT * FROM view_credential_1;

-- INSERT INTO CONTEST VALUES('1', 'T', 'D', NULL, NULL, TRUE);

-- INSERT INTO CONTEST_PARTICIPANTS VALUES(1, '1', 5, 5);

-- SELECT * FROM CONTEST_PARTICIPANTS;

-- CREATE VIEW QueraEcoPlus.view_contest_test_2 AS SELECT * FROM CONTEST 
    -- WHERE CONTEST_ID IN (SELECT CONTEST_ID FROM CONTEST_PARTICIPANTS WHERE USER_ID = 1);

-- SELECT * FROM view_contest_test_1;

-- SELECT * FROM CV;

-- SELECT * FROM ACTIVITY_HISTORY_CONTEST;

-- SELECT * FROM INFORMATION_SCHEMA.TRIGGERS;
