-- DROP DATABASE QueraEcoPlus;

SELECT * FROM USER;

INSERT INTO CONTEST VALUES('1', 'T', 'D', NULL, NULL, TRUE);

INSERT INTO CONTEST_PARTICIPANTS VALUES(1, '1', 5, 5);

SELECT * FROM CONTEST_PARTICIPANTS;

-- CREATE VIEW QueraEcoPlus.view_contest_test_2 AS SELECT * FROM CONTEST 
    -- WHERE CONTEST_ID IN (SELECT CONTEST_ID FROM CONTEST_PARTICIPANTS WHERE USER_ID = 1);

-- SELECT * FROM view_credential_1;

-- SELECT * FROM view_contest_test_1;

SELECT * FROM CV;

SELECT * FROM ACTIVITY_HISTORY_CONTEST;

UPDATE CONTEST_PARTICIPANTS SET CONTEST_PARTICIPANTS.RNK = 3, CONTEST_PARTICIPANTS.SCORE = 99
            WHERE USER_ID = 1;

INSERT INTO PROBLEM VALUES('1', 'PROB_TITE', 'DES_FILE', 2);

SELECT * FROM PROBLEM;

INSERT INTO SUBMISSION VALUES(NULL, '1', 1, 'SUB_FILE1', 60);

SELECT * FROM SUBMISSION;

SELECT * FROM ACTIVITY_HISTORY_PROBLEMS;

INSERT INTO COMPANY VALUES('company1', 'comp_add1', 'comp_name1', 'comp_info1',
                                'phone1', NULL, NULL);

INSERT INTO COMPANY VALUES('company2', 'comp_add2', 'comp_name2', 'comp_info2',
                                'phone2', NULL, NULL);


INSERT INTO ADVERTISEMENT VALUES('company1', 'add1', 'info1', 1400, FALSE, 2, NULL, NULL);

INSERT INTO ADVERTISEMENT VALUES('company2', 'add1', 'info2', 1401, FALSE, 3, NULL, NULL);

SELECT * FROM COMPANY;

SELECT * FROM ADVERTISEMENT;

INSERT INTO REQUESTS VALUES(1, 'company1', 'add1', 'status1');

INSERT INTO SKILLS VALUES('skill1', 'skill1type');

INSERT INTO CV_SKILLS VALUES(1, 'skill1', 2);


INSERT INTO ADV_RELATIVE_SKILLS VALUES('company1', 'add1', 'skill1');

INSERT INTO ADV_RELATIVE_SKILLS VALUES('company2', 'add1', 'skill1');

SELECT * FROM ADV_RELATIVE_SKILLS;

SELECT * FROM NOTIFICATION;

SELECT * FROM USER_NOTIFICATION;

SELECT * FROM NEW_ADD_NOTIF;
